CREATE TABLE movie (
  id                INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Helps auto-generate IDs.
  original_language VARCHAR,
  title             VARCHAR,
  popularity        DOUBLE PRECISION,
  release_date      DATE,
  runtime           INT,
  vote_average      DOUBLE PRECISION,
  vote_count        INT
);


CREATE TABLE genre (
  genre_id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  genre_name        VARCHAR
);

CREATE TABLE moviegenre (
  movie_id          INT REFERENCES movie(id),
  genre_id          INT REFERENCES genre(genre_id)
);


CREATE TABLE character (
  movie_id       INT REFERENCES movie(id),
  actor_id       INT,
  cast_id        INT,
  character_name VARCHAR,
  gender         INT
)

CREATE TABLE actor (
  actor_id       INT REFERENCES character(actor_id),
  name           VARCHAR
);

CREATE TABLE keyword (
  keyword_id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  keyword_name      VARCHAR
);
CREATE TABLE moviekeyword (
  movie_id          INT REFERENCES movie(id),
  keyword_id        INT REFERENCES keyword(keyword_id)
);

