CREATE TABLE movie (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Helps auto-generate IDs.
  original_language VARCHAR,
  title VARCHAR,
  popularity DOUBLE PRECISION,
  release_date DATE,
  runtime INT,
  vote_average DOUBLE PRECISION,
  vote_count INT
);

-- CREATE TABLE rating (
--   movie_id INT REFERENCES movie(id),
--   viewer_id INT, -- There is no actual viewer table because all we have is an ID.
--   rating INT,
--   date_rated DATE
-- );

-- CREATE TABLE credit (
--   movie_id INT REFERENCES movie(id),
  
-- )